updating the validations file to include the os test and the python test

diff --git a/.github/workflows/validations.yml b/.github/workflows/validations.yml
--- a/.github/workflows/validations.yml
+++ b/.github/workflows/validations.yml
@@ -10,10 +10,16 @@ jobs:
     runs-on: ubuntu-latest
     strategy:
       matrix:
-        python-version: ["3.10"]
+        python-version: ["3.10", "3.11"]
 
     steps:
       - uses: actions/checkout@v4
+      - name: Test OS
+        run: |
+          if [ "$RUNNER_OS" != "Linux"]; then
+            echo "Not running on Linux. Failing."
+            exit 1
+          fi
       - name: Set up Python ${{ matrix.python-version }}
         uses: actions/setup-python@v4
         with:
@@ -21,6 +27,12 @@ jobs:
       - name: Install dependencies
         run: |
           make update
+      - name: Test Python version
+        run: |
+           if [[ "$python_version" != "Python 3.10"* && $python_version != "Python 3.11"*]]; then
+             echo "This requires python version 3.10 or 3.11 the current version is : $python_version"
+             exit 1
+           fi
       - name: Test with pytest
         run: |
           make test
